#!/bin/bash
#SBATCH -J particle-gpu
#SBATCH -o particle-gpu.stdout
#SBATCH -n 1
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:k80:1
#SBATCH -t 00:10:00
./gpu-queue -n 2000 -o gpu_q.txt
./gpu-queue -n 4000 -o gpu_q.txt
./gpu-queue -n 8000 -o gpu_q.txt
./gpu-queue -n 16000 -o gpu_q.txt
./gpu-queue -n 32000 -o gpu_q.txt
./autocorrect -s gpu_q.txt
