#!/bin/bash
#SBATCH -J particle-gpu
#SBATCH -o particle-gpu.stdout
#SBATCH -n 1
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:k80:1
#SBATCH -t 00:10:00
./naive-gpu -n 2000 -o naive-gpu.txt
./naive-gpu -n 4000 -o naive-gpu.txt
./naive-gpu -n 8000 -o naive-gpu.txt
./naive-gpu -n 16000 -o naive-gpu.txt
./naive-gpu -n 32000 -o naive-gpu.txt
./autocorrect -s naive-gpu.txt